"use client";
import { useEffect, useState } from "react";
type Question = { id: number; content: string; options: string[] }; type Quiz = { id: string; expiresAt: string; questions: Question[] };
export function QuizApp() { const [profile, setProfile] = useState({ name: "", dateOfBirth: "", examGoal: "" }); const [quiz, setQuiz] = useState<Quiz | null>(null); const [position, setPosition] = useState(0); const [answers, setAnswers] = useState<Record<number, string>>({}); const [seconds, setSeconds] = useState(600); const [result, setResult] = useState<{ score: number; total: number } | null>(null); const [error, setError] = useState("");
  async function submit() { if (!quiz || result) return; const res = await fetch(`/api/quiz/${quiz.id}/submit`, { method: "POST" }); if (res.ok) setResult(await res.json()); }
  useEffect(() => { if (!quiz || result) return; const id = setInterval(() => { const left = Math.max(0, Math.ceil((new Date(quiz.expiresAt).getTime() - Date.now()) / 1000)); setSeconds(left); if (!left) void submit(); }, 1000); return () => clearInterval(id); }, [quiz, result]);
  async function begin() { const res = await fetch("/api/quiz/start", { method: "POST" }); const body = await res.json(); if (!res.ok) return setError(body.error); setQuiz(body); }
  async function finishProfile(e: React.FormEvent) { e.preventDefault(); const res = await fetch("/api/profile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); if (!res.ok) return setError((await res.json()).error); void begin(); }
  async function choose(questionId: number, value: string) { setAnswers((current) => ({ ...current, [questionId]: value })); if (quiz) await fetch(`/api/quiz/${quiz.id}/answer`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questionId, selectedAnswer: value }) }); }
  if (result) return <main className="center card"><p className="eyebrow">Quiz complete</p><h1>{result.score} / {result.total}</h1><p>Your score is saved for future analytics.</p></main>;
  if (!quiz) return <main className="center card"><p className="eyebrow">Exam Mate</p><h1>Let’s personalize your quiz.</h1><form onSubmit={finishProfile}><input required placeholder="Your name" value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} /><input required type="date" value={profile.dateOfBirth} onChange={(e) => setProfile({ ...profile, dateOfBirth: e.target.value })} /><input required placeholder="Competitive exam you’re preparing for" value={profile.examGoal} onChange={(e) => setProfile({ ...profile, examGoal: e.target.value })} /><button>Start my 10-minute quiz</button></form>{error && <p className="error">{error}</p>}</main>;
  const question = quiz.questions[position]; return <main className="quiz"><header><span>Question {position + 1} of 10</span><strong>{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, "0")}</strong></header><div className="progress"><i style={{ width: `${((position + 1) / 10) * 100}%` }} /></div><section className="card"><p>{question.content}</p><div className="options">{question.options.map((option) => <button className={answers[question.id] === option ? "selected" : ""} key={option} onClick={() => void choose(question.id, option)}>{option}</button>)}</div></section><footer><button disabled={!position} onClick={() => setPosition(position - 1)}>Back</button>{position === 9 ? <button onClick={() => void submit()}>Submit quiz</button> : <button onClick={() => setPosition(position + 1)}>Skip / Next</button>}</footer></main>; }
