export const encouragements = [
  "A steady routine can carry you farther than one perfect day.",
  "You showed up for your goal today. Keep that promise tomorrow too.",
  "Every answer reviewed is one less surprise on exam day.",
  "Small practice sessions become real confidence over time.",
  "Your next question is another chance to understand the pattern.",
  "Progress is built by returning, especially on ordinary days.",
  "A difficult question is useful when you stay with it.",
  "Keep your focus on the next ten minutes, not the whole syllabus.",
  "One completed set is proof that your preparation is moving.",
  "You do not need to know everything today; you need to keep learning.",
  "Accuracy grows when you give yourself time to notice the details.",
  "Your future score is shaped by the habits you practise now.",
  "The questions you miss today can become the ones you master tomorrow.",
  "A calm review is part of strong preparation.",
  "You are building recall one thoughtful attempt at a time.",
  "Returning tomorrow is more important than chasing a perfect streak.",
  "Your effort counts, even when the result is not what you hoped for.",
  "Keep collecting small wins; they add up quietly.",
  "Good preparation is less about pressure and more about repetition.",
  "Give the next topic your full attention, then let it go.",
  "You are learning how the exam thinks, one question at a time.",
  "Each honest attempt gives you a clearer place to begin again.",
  "A score is feedback for your plan, not a verdict on your ability.",
  "The work you repeat becomes the confidence you feel later.",
  "Stay patient with the subjects that take longer to settle.",
  "Your consistency is a skill, and you are practising it now.",
  "A focused session today makes tomorrow’s start easier.",
  "Keep going gently; strong routines do not need dramatic moments.",
  "Every topic you revisit becomes a little more familiar.",
  "The right pace is the pace you can return to tomorrow.",
  "You are allowed to learn slowly and still make meaningful progress.",
  "Finish the set, learn the lesson, and carry it forward.",
  "Practice turns uncertainty into something you can work with.",
  "Your preparation gets stronger each time you choose to begin.",
  "A missed answer can point directly to your next improvement.",
  "Keep the goal close and the next step simple.",
  "Today’s effort belongs to the student you are becoming.",
  "You are not behind; you are in the middle of building your rhythm.",
  "Real improvement is often quiet before it becomes visible.",
  "Trust the routine enough to return to it.",
  "One thoughtful review can be worth more than rushing into another set.",
  "You are training your attention as much as your memory.",
  "The habit of showing up is already a result worth keeping.",
  "Give yourself credit for doing the work that compounds.",
  "Take the lesson from today and leave the pressure behind.",
  "Each completed quiz adds another brick to your preparation.",
  "Your next attempt starts with what you learned from this one.",
  "The exam rewards preparation, and preparation rewards patience.",
  "Keep your promise to the next version of yourself.",
  "You are building more than a score: you are building readiness.",
] as const;

export function getEncouragement(seed: string) {
  let hash = 0;
  for (let index = 0; index < seed.length; index += 1) hash = (hash * 31 + seed.charCodeAt(index)) | 0;
  return encouragements[Math.abs(hash) % encouragements.length];
}
